[build-system]
requires = ["hatchling >= 1.26", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "carmela-code"
version = "0.1.0"
description = "A Python library for solving the one-electron one-dimensional Time-Dependent Schrödinger Equation (TDSE)"
authors = [
    {name = "Alex de la Calle", email = "alejandrodelacallenegro@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "palettable>=3.3.3",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "typer>=0.20.0",
]

[tool.hatch.build.targets.wheel]
packages = ["lib/carmela"]
